name: source_deploy

on:
  push:
    branches:
      - latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/551558020406/locations/global/workloadIdentityPools/example-pool/providers/example-gh-provider'
        service_account: 'my-service-account@glasnt-appdevrepro-2194.iam.gserviceaccount.com'

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        source: '.'
        region: us-central1
        service: boo
